import "../../(navbar)/globals.css";
import localFont from "next/font/local";

const noto = localFont({
  src: [
    {
      path: '../../(navbar)/fonts/NotoSansArabic-Thin.ttf',
      weight: '100'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-ExtraLight.ttf',
      weight: '200'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-Light.ttf',
      weight: '300'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-Medium.ttf',
      weight: '500'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-SemiBold.ttf',
      weight: '600'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-Bold.ttf',
      weight: '700'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-ExtraBold.ttf',
      weight: '800'
    },
    {
      path: '../../(navbar)/fonts/NotoSansArabic-Black.ttf',
      weight: '900'
    },
  ],
  variable: '--font-noto'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${noto.variable} antialiased bg-whiteBG h-svh`}>
        {children}
      </body>
    </html>
  );
}
