import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
const noto = localFont({
  src: [
    {
      path: './fonts/NotoSansArabic-Thin.ttf',
      weight: '100'
    },
    {
      path: './fonts/NotoSansArabic-ExtraLight.ttf',
      weight: '200'
    },
    {
      path: './fonts/NotoSansArabic-Light.ttf',
      weight: '300'
    },
    {
      path: './fonts/NotoSansArabic-Regular.ttf',
      weight: '400'
    },
    {
      path: './fonts/NotoSansArabic-Medium.ttf',
      weight: '500'
    },
    {
      path: './fonts/NotoSansArabic-SemiBold.ttf',
      weight: '600'
    },
    {
      path: './fonts/NotoSansArabic-Bold.ttf',
      weight: '700'
    },
    {
      path: './fonts/NotoSansArabic-ExtraBold.ttf',
      weight: '800'
    },
    {
      path: './fonts/NotoSansArabic-Black.ttf',
      weight: '900'
    },
  ],
  variable: '--font-noto'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${noto.variable} antialiased bg-whiteBG`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
